### ISSUE TITLE
引用资源500错误

### ISSUE THREAD

**Issue by GeekMakerSun** [litepress/LitePress#22]
登录后台 严重错位  
资源访问500错误 https://a2.wp-china-yes.net/WordPress@5.8.0.1-RC1%E3%80%8C%E4%B8%83%E5%A4%95%E3%80%8D/wp-includes/css/dashicons.min.css?ver=5.8.0.1-RC1%E3%80%8C%E4%B8%83%E5%A4%95%E3%80%8D

**Comment by sunxiyuan** [comment]
不好意思，我的锅，没有排除RC版的静态资源接管，稍等一会就推送一个更新（半小时内）在后台更新下wp china yes即可

**Comment by sunxiyuan** [comment]
更新已推送
